bloggy_project/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<url>/', views.PostDetailView.as_view(), name='post'),
]

bloggy_project/bloggy_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('blog', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloggy_project/blog/models.py
from django.db import models

class Post(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    tag = models.CharField(max_length=20, blank=True, null=True)
    image = models.ImageField(upload_to="images", blank=True, null=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

bloggy_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post
from django.views import generic
from vanilla import ListView, DetailView

import re


class IndexView(generic.ListView):

    template_name = 'blog/index.html'
    context_object_name = 'latest_posts'

    def get_queryset(self):

        posts = Post.objects.all().order_by('-created_at')
        for post in posts:
            post.url = re.sub(' ', '_', post.title)
        return posts


class PostDetailView(DetailView):

    def get(self, request, *args, **kwargs):

        post = get_object_or_404(Post, title=kwargs['url'].replace('_', ' '))
        post.views += 1
        post.save()
        return render(request,
                     'blog/post.html',
                     {'single_post': post})

bloggy_project/blog/templates/_base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <title>Bloggy: a blog app</title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta name="description" content="">
   <meta name="author" content="">

   <!-- Le styles -->
   <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/yeti/bootstrap.min.css" rel="stylesheet">
   <style>
     body {
       padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
     }
   </style>
   <script src="http://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript"></script>
    {% block extrahead %}
    {% endblock %}
   <script type="text/javascript">
    $(function(){
      {% block jquery %}
      {% endblock %}
    });
   </script>
 </head>

 <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/blog">Bloggy</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/blog/add_post/">Add Post</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

   <div id="messages">
     {% if messages %}
       {% for message in messages %}
         <div class="alert alert-{{message.tags}}">
           <a class="close" data-dismiss="alert">×</a>
           {{message}}
         </div>
       {% endfor %}
     {% endif %}
   </div>

   <div class="container">
   {% block content %}
   {% endblock %}
   </div> <!-- /container -->
 </body>
</html>

bloggy_project/blog/templates/blog/index.html
{% extends '_base.html' %}

{% block content %}
{% if latest_posts %}
<ul>
{% for post in latest_posts %}
<h3><a href="{% url 'blog:post' post.url %}">{{ post.title }}</a></h3>
<p><em>{{ post.created_at }}</em></p>
<p>{{ post.content }}</p>
<br>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

bloggy_project/blog/templates/blog/post.html
{% extends '_base.html' %}
{% block content %}
<h2>{{ single_post.title }}</h2>
<ul>
<p><em>{{ single_post.created_at }}</em></p>
<p>{{ single_post.content }}</p>
<p>Tag: {{ single_post.tag }}</p>
<p>Views: {{ single_post.views }}</p>
<br>
<p>
{% if single_post.image %}
<img src="/media/{{ single_post.image }}">
{% endif %}
</p>
</ul>
<p>Had enough? Return <a href="/">home</a>.</p><br/>
{% endblock %}